#!/usr/bin/env python3
"""Generate `mlobs_core.v_sink_logs`: every sink log table, unioned, portable.

The Log Router names one BigQuery table per Cloud Logging log id, so the set of
tables differs by project and grows over time as new components start logging.
Hard-coding the list would make the model non-portable and quietly stale, so the
view is generated by discovering tables from INFORMATION_SCHEMA.

A table counts as a log table when it has `resource` and `timestamp` columns and
is not on the deny-list below. The deny-list is needed because
`pod_labels_backfill` also has both and would otherwise be unioned in twice --
once here and once directly in dim_pod.

Two schema hazards make this trickier than a plain UNION:

  * `resource`, `labels` and `json_payload` are STRUCTs whose *field sets differ
    per table* -- an audit log's resource.labels has nothing in common with a
    k8s_container's. UNION ALL rejects that outright, so every branch converts
    them to JSON, which is one type regardless of contents. Consumers use
    JSON_VALUE and get NULL for keys a given row does not have.
  * Column presence also varies: `labels` or `json_payload` may be absent
    entirely if no entry ever carried them. Each branch emits a typed NULL for
    whatever its table lacks rather than failing the whole view.

And one naming trap worth spelling out: the BigQuery **sink** writes LogEntry
fields in camelCase (`textPayload`, `jsonPayload`, `receiveTimestamp`) while the
Log Analytics **linked dataset** uses snake_case (`text_payload`, ...). Looking
for only one spelling silently produced a view where every payload column was
NULL, which in turn gave fact_event 1,659 app_error and 1,308 k8s_event rows
with empty summaries. Each canonical column therefore lists both spellings.
"""

import argparse
import json
import subprocess
import sys

# canonical output column -> (candidate source spellings, wrap, NULL cast).
# `wrap` is TO_JSON for STRUCT columns so branches stay union-compatible.
COLUMNS = {
    "resource":          (["resource"],                        "TO_JSON", "JSON"),
    "labels":            (["labels"],                          "TO_JSON", "JSON"),
    "json_payload":      (["jsonPayload", "json_payload"],     "TO_JSON", "JSON"),
    "text_payload":      (["textPayload", "text_payload"],     None,      "STRING"),
    "severity":          (["severity"],                        None,      "STRING"),
    "insert_id":         (["insertId", "insert_id"],           None,      "STRING"),
    "receive_timestamp": (["receiveTimestamp", "receive_timestamp"], None, "TIMESTAMP"),
}

# Tables that live in mlobs_raw but are not sink output.
DENY = {"pod_labels_backfill", "metric_samples", "mldiag_runs", "mldiag_events"}


def bq_json(project, sql):
    out = subprocess.run(
        ["bq", f"--project_id={project}", "query", "--use_legacy_sql=false",
         "--format=json", "--max_rows=10000", sql],
        capture_output=True, text=True)
    if out.returncode != 0:
        sys.exit(f"query failed:\n{out.stderr}")
    return json.loads(out.stdout or "[]")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--project", required=True)
    ap.add_argument("--raw-dataset", default="mlobs_raw")
    ap.add_argument("--core-dataset", default="mlobs_core")
    ap.add_argument("--dry-run", action="store_true",
                    help="print the DDL instead of running it")
    args = ap.parse_args()

    cols = bq_json(args.project, f"""
        SELECT table_name, column_name, data_type
        FROM `{args.project}.{args.raw_dataset}.INFORMATION_SCHEMA.COLUMNS`
        WHERE table_name IN (
          SELECT table_name
          FROM `{args.project}.{args.raw_dataset}.INFORMATION_SCHEMA.TABLES`
          WHERE table_type = 'BASE TABLE')
    """)

    schema = {}
    for row in cols:
        schema.setdefault(row["table_name"], set()).add(row["column_name"])

    log_tables = sorted(t for t, c in schema.items()
                        if "resource" in c and "timestamp" in c and t not in DENY)
    if not log_tables:
        sys.exit(f"no sink log tables found in {args.raw_dataset} -- "
                 "has the sink delivered anything yet?")

    branches = []
    for table in log_tables:
        present = schema[table]
        # the sink table name is the log id with non-alphanumerics replaced
        select = [f"  '{table}' AS log_id", "  timestamp"]
        for col, (candidates, wrap, typ) in COLUMNS.items():
            source = next((c for c in candidates if c in present), None)
            if source is None:
                select.append(f"  CAST(NULL AS {typ}) AS {col}")
            elif wrap:
                select.append(f"  {wrap}({source}) AS {col}")
            else:
                select.append(f"  {source} AS {col}")
        branches.append("SELECT\n" + ",\n".join(select)
                        + f"\nFROM `{args.project}.{args.raw_dataset}.{table}`")

    ddl = (f"CREATE OR REPLACE VIEW `{args.project}.{args.core_dataset}.v_sink_logs` AS\n"
           + "\nUNION ALL\n".join(branches) + ";\n")

    if args.dry_run:
        print(ddl)
        return

    result = subprocess.run(
        ["bq", f"--project_id={args.project}", "query", "--use_legacy_sql=false", ddl],
        capture_output=True, text=True)
    if result.returncode != 0:
        sys.exit(f"failed to create view:\n{result.stderr}")
    print(f"  v_sink_logs over {len(log_tables)} tables: {', '.join(log_tables)}")


if __name__ == "__main__":
    main()
